mlm/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
			password_reset,
			password_reset_done,
			password_reset_confirm,
			password_reset_complete,
			password_change,
			password_change_done,
		)
from django.conf import settings
admin.autodiscover()
from django.views.generic import TemplateView
from company.models import ProjectSitemap
from company import views as company
from account import views as account
from blog import views as blog
from chat import views as chat
from banners import views as banner
from django.contrib.auth import views as auth

from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'projects': ProjectSitemap,
}

urlpatterns = [
	# url(r'^home/', company.index, name='index'),
	url(r'^', include('company.urls')),
    # accoun vies
	url(r'^login/', auth.login, {'template_name': 'account/login.html'}, name='login'),
	url(r'^logout/', account.logout, name='logout'),
	url(r'^register/', account.register, name='register'),
	url(r'^accounts/profile/', account.profile, name='profile'),
	url(r'^accounts/password/change/$', password_change, name="password_change"),
	url(r'^accounts/password_change_done', password_change_done, name="password_change_done"),
    url(r'^reset_password/$', password_reset, name="password_reset"),
    url(r'^accounts/password/change/done/$', password_reset_done, name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset_password/complete/', password_reset_complete, name="password_reset_complete"),
    url(r'^accounts/settings/', account.settings, name="settings"),
    url(r'^accounts/edit_user/', account.edit_user, name="edit_user"),
    url(r'^accounts/edit_foto/', account.edit_foto, name="edit_foto"),
    ########## company views ###################
	# url(r'^company/$', company.company_all, name="company_all"),
	# url(r'^company_detail/(?P<slug>[?a-z=A-Z0-9_.-]*)/$', company.company_detail, name='company_detail'),
	# url(r'^company_filter/(?P<id>[?a-z=A-Z0-9_.-]*)/$', company.company_filter, name='company_filter'),
	# url(r'^company/(?P<status>[?a-z=A-Z0-9_.-]*)/$', company.status_filter, name='status_filter'),
	# url(r'^listing/(?P<id>[?a-z=A-Z0-9_.-]*)/$', company.listing, name='listing'),
	# url(r'^category/(?P<id>[?a-z=A-Z0-9_.-]*)/(?P<status>[?a-z=A-Z0-9_.-]*)/$', company.category_filter, name='category_filter'),
	# url(r'^company_registration/$', company.company_registration, name='company_registration'),
	# url(r'^wizzard_company/$', company.wizzard_company, name="wizzard_company"),
	# url(r'^company/error/$', company.wizzard_pay_error, name='wizzard_pay_error'),
	# url(r'^scam/(?P<slug>[?a-z=A-Z0-9_.-]*)/$', company.scam, name='scam'),
	url(r'^search/', company.search, name="search"),
    # Notification
    url(r'^notification/', include('notifications.urls', namespace="notification")),
    # blog views
    url(r'^blog/', include('blog.urls')),
	# url(r'^blog/', blog.blog, name='blog'),
	# url(r'^blog_single/(?P<slug>[?a-z=A-Z0-9_.-]*)/$', blog.blog_single, name='blog_single'),
	# url(r'^faq/', blog.faq, name='faq'),
    # Chat Views
	url(r'^chat/', chat.chat, name='chat'),
	url(r'^post/', chat.post, name='post'),
	url(r'^messages/', chat.messages, name='messages'),
	# Banner views
	url(r'^banners_registration/$', banner.add_banner, name="add_banner"),
    # robots
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type="text/plain")),
    # Sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # Admin views
	url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     # static files (images, css, javascript, etc.)
#     urlpatterns += [
#         url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#         	'document_root': settings.MEDIA_ROOT})
#         ]

banners/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save

# Create your models here.

pay_choice = (
	("5", "Верхний"),
	("3", "Центральный"),
	("1", "Боковой")
)
	
class BannerManager(models.Manager):
	def active(self, *args, **kwargs):
		return super(BannerManager, self).filter(continue_date__gt=timezone.now()).filter(active=True)

class Banner(models.Model):
	pay = models.CharField(choices=pay_choice, max_length=50, verbose_name="Баннер")
	site = models.URLField(verbose_name="Сылка на проект")
	email = models.EmailField(verbose_name="Контактный адрес")
	img_url = models.TextField(verbose_name="Сылка", max_length=250)
	update = models.DateField(auto_now=True)
	continue_date = models.DateField(verbose_name="Дата окончания", blank=True, null=True)
	time = models.PositiveIntegerField(verbose_name="Количество дней")
	money = models.CharField(max_length=50, verbose_name="Окончатильная сума")
	active = models.BooleanField(default=False, verbose_name="Статус розмищения")

	objects = BannerManager()

	class Meta:
		verbose_name_plural = "Баннер"
		ordering = ("email", "update", "continue_date")


	def __unicode__(self):
		return self.email


	def get_date(self):
		new_date = self.continue_date
		days = self.time
		newDate = self.update
		new_date = newDate + datetime.timedelta(days=days)
		return new_date


def get_date(instance):
	timeNow = datetime.datetime.now()
	continue_date = instance.continue_date
	time = instance.time
	if time is not 0:
		continue_date = timeNow + datetime.timedelta(days=time)
	else:
		continue_date = timeNow
	return continue_date

def pre_save_date(sender, instance, *args, **kwargs):
	if not instance.continue_date:
		instance.continue_date = get_date(instance)

pre_save.connect(pre_save_date, sender=Banner)

banners/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Banner


class LoadBanner(forms.ModelForm):
	money = forms.CharField(widget=forms.TextInput(attrs={'readonly': True}), label="К оплате")
	class Meta:
		model = Banner
		fields = ('pay', 'site', 'email', 'img_url', 'time', 'money')

banners/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import *
from .forms import LoadBanner
# Create your views here.

def add_banner(request, *args, **kwargs):
	if request.POST:
		form = LoadBanner(request.POST or None, request.FILES or None)
		if form.is_valid():
			post_data = form.cleaned_data
			banner = Banner.objects.create(**post_data)
			return HttpResponseRedirect('/')
	else:
		form = LoadBanner()
	template_data = {'form': form}
	return render(request, 'banner/add_banner.html', template_data)


def wizzard_banner(request):
	template_data = {}
	return render(request, 'banner/wizzard_banner.html')

templates/banner/add_banner.html
{% extends 'mlm_base_index.html' %}
{% load crispy_forms_tags %}

{% block title %} Разместить баннер {% endblock %}

{% block content %}

<div class="content animate-panel">
	<div class="row">
		<div class="col-md-12">
			<div class="hpanel">
				<div class="panel-heading">
					<h3>Форма розмищения баннера</h3>
				</div>
				<div class="panel-body">
					<div class="table-responsive">
		                <table cellpadding="1" cellspacing="1" class="table">
		                    <thead>
		                    <tr>
		                        <th>Баннер</th>
		                        <th>Расположение</th>
		                        <th>Стоимость</th>
		                    </tr>
		                    </thead>
		                    <tbody>
		                    <tr>
		                        <td>Вверхний</td>
		                        <td>Вверху (Динамичный 728x90)</td>
		                        <td>$5/день</td>
		                        
		                    </tr>
		                    <tr>
		                        <td>Центральный</td>
		                        <td>В центре (Динамичный 468х60)</td>
		                        <td>$3/день</td>
		                        
		                    </tr>
		                    <tr>
		                        <td>Нижний</td>
		                        <td>В низу (Динамичный 125х125)</td>
		                        <td>$1/день</td>
		                        
		                    </tr>
		                    </tbody>
		                </table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="content animate-panel">
	<div class="row">
		<div class="col-md-12">
			<div class="hpanel">
				<div class="panel-body">
					<form class="form-horizontal" method="post" action="." enctype="multipart/form-data">
						{% csrf_token %}
						{{form|crispy}}
						<input type="hidden" name="price" value="0" id='price'>
						
				        <button type="submit" class="btn btn-primary" disabled>Готово</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block custom_scripts %}
<script type="text/javascript">
	$(document).ready(function(){
		$('select').change(function(){
			var pay = $(this).val();
			$("#price").val(pay);
			$("#id_money").val(0).prop('value', 0);
			$("#id_time").val(0);
		});

		$("#id_time").keyup(function(){
			var days = $(this).val();
			var price = $("#price").val();
			var paypal = days * price;
			
			if (paypal > 0) {
				$('button').prop('disabled', false);
			} else {
				$('button').prop('disabled', true);
			}
			$("#id_money").attr('value', paypal).val(paypal);
		});
	});
</script>
{% endblock %}