mlm/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
			password_reset,
			password_reset_done,
			password_reset_confirm,
			password_reset_complete,
			password_change,
			password_change_done,
		)
from django.conf import settings
admin.autodiscover()
from django.views.generic import TemplateView
from company.models import ProjectSitemap
from company import views as company
from account import views as account
from blog import views as blog
from chat import views as chat
from banners import views as banner
from django.contrib.auth import views as auth

from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'projects': ProjectSitemap,
}

urlpatterns = [
	# url(r'^home/', company.index, name='index'),
	url(r'^', include('company.urls')),
    # accoun vies
	url(r'^login/', auth.login, {'template_name': 'account/login.html'}, name='login'),
	url(r'^logout/', account.logout, name='logout'),
	url(r'^register/', account.register, name='register'),
	url(r'^accounts/profile/', account.profile, name='profile'),
	url(r'^accounts/password/change/$', password_change, name="password_change"),
	url(r'^accounts/password_change_done', password_change_done, name="password_change_done"),
    url(r'^reset_password/$', password_reset, name="password_reset"),
    url(r'^accounts/password/change/done/$', password_reset_done, name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset_password/complete/', password_reset_complete, name="password_reset_complete"),
    url(r'^accounts/settings/', account.settings, name="settings"),
    url(r'^accounts/edit_user/', account.edit_user, name="edit_user"),
    url(r'^accounts/edit_foto/', account.edit_foto, name="edit_foto"),
    ########## company views ###################
	# url(r'^company/$', company.company_all, name="company_all"),
	# url(r'^company_detail/(?P<slug>[?a-z=A-Z0-9_.-]*)/$', company.company_detail, name='company_detail'),
	# url(r'^company_filter/(?P<id>[?a-z=A-Z0-9_.-]*)/$', company.company_filter, name='company_filter'),
	# url(r'^company/(?P<status>[?a-z=A-Z0-9_.-]*)/$', company.status_filter, name='status_filter'),
	# url(r'^listing/(?P<id>[?a-z=A-Z0-9_.-]*)/$', company.listing, name='listing'),
	# url(r'^category/(?P<id>[?a-z=A-Z0-9_.-]*)/(?P<status>[?a-z=A-Z0-9_.-]*)/$', company.category_filter, name='category_filter'),
	# url(r'^company_registration/$', company.company_registration, name='company_registration'),
	# url(r'^wizzard_company/$', company.wizzard_company, name="wizzard_company"),
	# url(r'^company/error/$', company.wizzard_pay_error, name='wizzard_pay_error'),
	# url(r'^scam/(?P<slug>[?a-z=A-Z0-9_.-]*)/$', company.scam, name='scam'),
	url(r'^search/', company.search, name="search"),
    # Notification
    url(r'^notification/', include('notifications.urls', namespace="notification")),
    # blog views
    url(r'^blog/', include('blog.urls')),
	# url(r'^blog/', blog.blog, name='blog'),
	# url(r'^blog_single/(?P<slug>[?a-z=A-Z0-9_.-]*)/$', blog.blog_single, name='blog_single'),
	# url(r'^faq/', blog.faq, name='faq'),
    # Chat Views
	url(r'^chat/', chat.chat, name='chat'),
	url(r'^post/', chat.post, name='post'),
	url(r'^messages/', chat.messages, name='messages'),
	# Banner views
	url(r'^banners_registration/$', banner.add_banner, name="add_banner"),
    # robots
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type="text/plain")),
    # Sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # Admin views
	url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     # static files (images, css, javascript, etc.)
#     urlpatterns += [
#         url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#         	'document_root': settings.MEDIA_ROOT})
#         ]

notifications/urls.py
from django.conf.urls import url

from .views import (
    FeedbackView,
    NotificationView
)

urlpatterns = [
    url(r'^feedback/$', FeedbackView.as_view(), name='feedback_view'),
    url(r'^mail_notifications/$', NotificationView.as_view(), name="notification_view"),
]

templates/footer.html
<footer class="footer">



  <div class="text-center">
    <strong>&copy 2017 Все права защищены, MLM-CONNECT</strong>
  </div>

</footer>

templates/header.html
<!-- Header -->
{% load static %}
<div id="header-top" class="hidden-xs">
    <div class="container">
        <div class="top-bar">
            <div class="pull-left sample-1right">
                <a href="{% url 'notification:feedback_view' %}">
                    <i class="fa fa-envelope"></i>
                    Написать нам: <span class="colored-text">mlmconnect01@gmail.com</span>
                </a>
            </div>
            <div class="pull-right">
                <ul class="list-inline top-social">
                    <li>Мы в социальных сетях:</li>
                    <li>
                        <a href="https://www.facebook.com/groups/monitoringmlmconnect/" target="_blank">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://vk.com/investing777" target="_blank">
                            <i class="fa fa-vk"></i>
                        </a>
                    </li>
                    <li>
                      <a href="https://www.instagram.com/mlmconnect/" target="_blank">
                        <i class="fa fa-instagram"></i>
                      </a>
                    </li>
                    <li>
                      <a href="https://twitter.com/mlmconnect01?lang=ru" target="_blank">
                        <i class="fa fa-twitter"></i>
                      </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="header">
    <div class="color-line">
    </div>
    <div id="logo" class="light-version">
        <a href="/">
        	<img src="{% static 'image/connect-05.png' %}" class="img-responsive" style="max-width: 54%; margin-left:20px;">
        </a>
    </div>
    <nav role="navigation">
        <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
        <div class="small-logo">
            <!--<span class="text-primary">MLM-CONNECT</span>-->
            MLM-CONNECT
        </div>
        <form role="search" class="navbar-form-custom" method="get" action="{% url 'search' %}">
        	{% csrf_token %}
            <div class="form-group">
                <input type="text" placeholder="Поиск" class="form-control" name="q">
            </div>
        </form>
        <div class="mobile-menu">
            <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
                <i class="fa fa-chevron-down"></i>
            </button>

            <div class="collapse mobile-navbar" id="mobile-collapse">
                <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                  <li>
                    <a class="" href="{% url 'profile' %}">Профиль</a>
                  </li>
                  <li>
                    <a class="" href="{% url 'logout' %}">Выход</a>
                  </li>
                {% else %}
                  <li>
                    <a class="" href="{% url 'login' %}">Вход</a>
                  </li>
                {% endif %}
                </ul>
            </div>
        </div>
        <div class="navbar-right">
            <ul class="nav navbar-nav no-borders">
                {% if user.is_staff %}
                <li class="dropdown">
                  <a class="dropdown-toggle label-menu-corner" href="#" data-toggle="dropdown" aria-expanded="false">
                    <i class="pe-7s-speaker"></i>
                    <span class="label label-success">
                      {{request_company.count}}
                    </span>
                  </a>
                  <ul class="dropdown-menu hdropdown notification animated flipInX">
                    {% for obj in request_company %}
                      <li>
                        <a>
                          <span class="label label-success">NEW</span> {{obj.company_name}}
                        </a>
                      </li>
                    {% endfor %}
                    <li class="summary"><a href="#">Смотреть больше</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" data-toggle="dropdown" aria-expanded="false" class="dropdown-toggle">
                    <i class="pe-7s-mail"></i>
                  </a>
                  <ul class="dropdown-menu hdropdown notification animated flipInx">
                    <li class="">
                      <a href="{% url 'notification:notification_view' %}">Email</a>
                    </li>
                  </ul>
                </li>
                {% endif %}
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                      <i class="pe-7s-keypad"></i>
                    </a>
                    <div class="dropdown-menu hdropdown bigmenu animated flipInX">
                      <table>
                          <tbody>
                          <tr>
                            <td>
                              <a href="{% url 'company_all' %}">
                                <i class="pe pe-7s-portfolio text-info"></i>
                                <h5>Все проекты</h5>
                              </a>
                            </td>
            								<td>
            									<a href="{% url 'company_registration' %}">
            										<i class="pe pe-7s-monitor text-warning"></i>
            										<h5>Добавить проект</h5>
            									</a>
            								</td>
                            <td>
                                <a href="{% url 'notification:feedback_view' %}">
                                    <i class="pe pe-7s-users text-success"></i>
                                    <h5>Обратная связь</h5>
                                </a>
                            </td>
                          </tr>
                          <tr>
                            <td>
                              <a href="{% url 'chat' %}">
                                <i class="pe pe-7s-comment text-info"></i>
                                <h5>Chat</h5>
                              </a>
                            </td>
            								<td>
            									<a href="{% url 'add_banner' %}">
            										<i class="pe pe-7s-albums text-warning"></i>
            										<h5>Добавить баннер</h5>
            									</a>
            								</td>
                            <td>
                              <a href="{% url 'faq' %}">
                                <i class="pe pe-7s-box1 text-success"></i>
                                <h5>F.A.Q</h5>
                              </a>
                            </td>
                          </tr>
                          </tbody>
                      </table>
                    </div>
                </li>
                <li>
                  <a href="#" id="sidebar" class="right-sidebar-toggle">
                    <i class="pe-7s-upload pe-7s-news-paper"></i>
                  </a>
                </li>
                {% if user.is_authenticated %}
                <li class="dropdown">
                	<a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    {{user.username}}
                  </a>
                	<ul class="dropdown-menu hdropdown animated flipInX">
                		<li>
                    		<a href="{% url 'profile' %}">
                    			<i class="fa fa-home"></i> Профиль
                    		</a>
                    	</li>
                    	<li>
                    		<a href="{% url 'settings' %}">
                    			<i class="fa fa-cog"> Настройки</i>
                    		</a>
                    	</li>
                		<li>
	                		<a href="{% url 'logout' %}">
	                        	<i class="pe-7s-upload pe-rotate-90"></i> Выход
	                    	</a>
                    	</li>
                	</ul>
                </li>
                {% else %}
                <li class="dropdown">
                    <a href="{% url 'login' %}">
                        <i class="pe-7s-upload pe-rotate-90"></i>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

templates/left_sidebar.html
{% load current_tags %}

<div class="col-lg-2 col-md-3">
  <div class="hpanel">
    <a href="{% url 'company_registration' %}" class="btn btn-success btn-block">
      Добавить проект
    </a>
  </div>



  <div class="hpanel hidden-sm">
    <div class="panel-heading hbuilt">
      <div class="panel-tools">
        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
        <a class="closebox"><i class="fa fa-times"></i></a>
      </div>
      <a href="{% url 'blog' %}">
        <i class="fa fa-news"></i> Последнии статьи
      </a>
    </div>
    <div class="panel-body no-padding">
      <ul class="list-group">
        {% for blog in last_blog %}
        <a href="{% url 'blog_single' blog.slug %}">
          <li class="list-group-item">{{blog.title}}</li>
        </a>
        {% endfor %}
      </ul>
    </div>
  </div>



</div>

templates/mlm_account_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}mlm-connect{% endblock %}</title>
    {% load crispy_forms_tags %}
    {% load static %}
    {% load i18n %}
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <!--<link rel="shortcut icon" type="image/ico" href="favicon.ico" />-->
    <!-- Vendor styles -->
    <link rel="stylesheet" href="{% static 'homer/vendor/fontawesome/css/font-awesome.css' %}" />
    <link rel="stylesheet" href="{% static 'homer/vendor/metisMenu/dist/metisMenu.css' %}" />
    <link rel="stylesheet" href="{% static 'homervendor/animate.css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'homer/vendor/bootstrap/dist/css/bootstrap.css' %}" />
    <!-- App styles -->
    <link rel="stylesheet" href="{% static 'homer/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css' %}" />
    <link rel="stylesheet" href="{% static 'homer/fonts/pe-icon-7-stroke/css/helper.css' %}" />
    <link rel="stylesheet" href="{% static 'homer/styles/style.css' %}">
  </head>
  <body class="blank">
    <!-- Simple splash screen-->
    <div class="splash">
      <div class="color-line"></div>
      <div class="splash-title">
        <h1>Homer - Responsive Admin Theme</h1>
        <p>Special AngularJS Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p>
        <img src="{% static 'homer/images/loading-bars.svg' %}" width="64" height="64" />
      </div>
    </div>
    <div class="color-line"></div>
    <div class="back-link">
        <a href="/" class="btn btn-primary">Back to Dashboard</a>
    </div>
    {% block breadcrumbs %}
    {% endblock %}
    {% block content %}

    {% endblock %}
    <!-- Vendor scripts -->
    <script src="{% static 'homer/vendor/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'homer/vendor/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'homer/vendor/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'homer/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'homer/vendor/metisMenu/dist/metisMenu.min.js' %}"></script>
    <script src="{% static 'homer/vendor/iCheck/icheck.min.js' %}"></script>
    <script src="{% static 'homer/vendor/sparkline/index.js' %}"></script>
    <!-- App scripts -->
    <script src="{% static 'homer/scripts/homer.js' %}"></script>
    {% block custom_scripts %}
    {% endblock %}
</body>
</html>

templates/navigation.html
<aside id="menu" style="top: 133px;">
  <div id="navigation">
    <ul class="nav" id="side-menu">
      <li class="active">
        <a href="{% url 'index' %}"> <span class="nav-label">Главная</span> <span class="label label-success pull-right"></span> </a>
      </li>
      <li>
        <a href="#"><span class="nav-label">Категории</span><span class="fa arrow"></span> </a>
        <ul class="nav nav-second-level collapse out" aria-expanded="true">
          {% for category in category_list %}
            <li><a href="{% url 'company_filter' category.id %}">{{category.name}}</a></li>
          {% endfor %}
        </ul>
      </li>
      <li>
        <a href="#"><span class="nav-label">Листинг</span><span class="fa arrow"></span></a>
        <ul class="nav nav-second-level collapse out" aria-expanded="true">
          {% for value in plan %}
            <li><a href="{% url 'listing' value.id %}">{{value.name}}</a></li>
          {% endfor %}
        </ul>
      </li>
      <li>
        <a href="{% url 'blog' %}"> <span class="nav-label">Статьи</span><span class="label label-success pull-right">NEW</span> </a>
      </li>
      {% if user.is_staff %}
        <li>
          <a href="{% url 'admin:index' %}">Admin</a>
        </li>
        {% endif %}
    </ul>
  </div>
</aside>

templates/right_sidebar.html
{% load current_tags %}

<div class="col-lg-3 col-md-3">
  <div class="hpanel">
    <a href="{% url 'company_registration' %}" class="btn btn-success btn-block">Добавить проект</a>
  </div>
  <!-- <div class="hpanel">
    <div class="panel-heading hbuilt">
      <div class="panel-tools">
          <a class="showhide"><i class="fa fa-chevron-up"></i></a>
          <a class="closebox"><i class="fa fa-times"></i></a>
      </div>
      <i class="fa fa-list"></i> Мониторинг
    </div>

    <div class="panel-body">
      <div class="panel-group" id="accordion">
        {% for category in category_list %}
          <div class="panel panel-default">
            <div class="panel-heading" id="heading{{forloop.counter}}">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{forloop.counter}}">
                    {{category.name}}
                </a>
              </h4>
            </div>
            <div id="collapse{{forloop.counter}}" class="panel-collapse collapse"  aria-labelledby="heading{{forloop.counter}}">
              <div class="panel-body no-padding">
                {% for s,i in status %}
                  <div class="list-group">
                    <a class="list-group-item" href="{% url 'category_filter' category.id s %}">
                      <span class="badge {{s|color_tag}}">
                        {{category|monitoring:s}}
                      </span>
                      {{i}}
                    </a>
                  </div>
                {% endfor %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div> -->
  <div class="hpanel">
    <div class="panel-heading hbuilt">
      <div class="panel-tools">
              <a class="showhide"><i class="fa fa-chevron-up"></i></a>
              <a class="closebox"><i class="fa fa-times"></i></a>
            </div>
      <i class="fa fa-list"></i> Мониторинг
    </div>
    <div class="panel-body no-padding">
      <ul class="list-group" id='accordion'>
        {% for category in category_list %}
            <li class="list-group-item" id="monitoring{{forloop.counter}}" role="tablist">
            <h4 class="panel-title">
              <a href="#collapse{{forloop.counter}}"
                data-toggle="collapse"
                data-parent="#accordion">
                {{category.name}}
              </a>
            </h4>
            <ul class="list-group panel-collapse collapse"
                id="collapse{{forloop.counter}}"
                role="tabpanel"
                aria-labelledby='monitoring{{forloop.counter}}'>
              {% for s,i in status %}
                <li class="list-group-item">
                  <a href="{% url 'category_filter' category.id s %}">
                    <span class="badge {{s|color_tag}}">
                      {{category|monitoring:s}}
                    </span>
                    {{i}}
                  </a>
                </li>
              {% endfor %}
            </ul>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="hpanel">
    <div class="panel-heading hbuilt">
      <div class="panel-tools">
          <a class="showhide"><i class="fa fa-chevron-up"></i></a>
          <a class="closebox"><i class="fa fa-times"></i></a>
      </div>
      <i class="fa fa-money text-success"></i> ПОСЛЕДНИЕ ВЫПЛАТЫ
    </div>
    <div class="panel-body no-padding">
      <div class="list-group">
      {% for company in payment %}
        <a href="{% url 'company_detail' company.company.slug %}" class="list-group-item">
          <h5 class="list-group-item-heading">{{company.company.company_name}}</h5>
          <p class="list-group-item-text">
            <span class="badge badge-success">{{company.value}}</span>
            <small class="">{{company.timestamp}}</small>
          </p>
        </a>
      {% endfor %}
      </div>
    </div>
  </div>
  <div class="hpanel">
    <div class="panel-heading hbuilt">
      <i class="fa fa-rub text-success"></i> РЕКЛАМА
    </div>
    <div class="panel-body">
      <center>
        <a href="https://linkslot.ru/link.php?id=156496" target="_blank">
          Купить ссылку здесь за
          <span id="linprice_156496"></span>
          руб.
        </a>
        <div id="linkslot_156496" style="margin: 10px 0;">
          <script src="https://linkslot.ru/lincode.php?id=156496" async></script>
        </div>
        <a href="https://linkslot.ru/?ref=hyipmonitoring" target="_blank">
          Поставить к себе на сайт
        </a>
      </center>
    </div>
  </div>
  <div class="hpanel">
    <div class="panel-heading hbuilt">
      <div class="panel-tools">
          <a class="showhide"><i class="fa fa-chevron-up"></i></a>
          <a class="closebox"><i class="fa fa-times"></i></a>
      </div>
      <i class="fa fa-history"></i> Последние скамы
    </div>
    <div class="panel-body no-padding">
      <div class="list-group">
      {% for company in company_list %}
        {% if company.status == 'close' %}
          <a href="{% url 'company_detail' company.slug %}" class="list-group-item">
            <h5 class="list-group-item-heading">{{company.company_name}}</h5>
            <p class="list-group-item-text">
              <span class="badge badge-danger">SCAM</span>
              <small class="">{{company.update|date:'SHORT_DATE_FORMAT'}}</small>
            </p>
          </a>
        {% endif %}
      {% endfor %}
      </div>
    </div>
  </div>
  <div class="hpanel">
    <div class="panel-body" align="center">
        <div class="down-banner">
            {% for down in banner %}
                {% if down.pay == '1' %}
                    {{down.img_url|safe}}
                {% endif %}
            {% endfor %}
        </div>
    </div>
  </div>
  <div class="hpanel">
    <div class="panel-heading hbuilt">
      <div class="panel-tools">
        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
        <a class="closebox"><i class="fa fa-times"></i></a>
      </div>
      <i class="pe pe-7s-display1 text-success"></i>
      Статистика
    </div>
    <div class="panel-body no-padding" align="center">
      <ul class="list-group">
        <li class="list-group-item">
          <div id="nlx"></div>
        </li>
        <li class="list-group-item">
          <span id="hotlog_counter"></span>
          <span id="hotlog_dyn"></span>
          <noscript>
            <a href="http://click.hotlog.ru/?2551119" target="_blank">
              <img src="http://hit2.hotlog.ru/cgi-bin/hotlog/count?s=2551119&im=407" border="0" alt="HotLog" title="HotLog">
            </a>
          </noscript>
        </li>
        <li class="list-group-item">
          <span id="openstat1"></span>
        </li>
        <li class="list-group-item">
          <span id="top100_widget"></span>
          <noscript>
            <img src="//counter.rambler.ru/top100.cnt?pid=4494629" alt="Топ-100" />
          </noscript>
        </li>
      	<li class="list-group-item">
      		<script type="text/javascript">
      			document.write("<a href='//www.liveinternet.ru/click' "+
      "target=_blank><img src='//counter.yadro.ru/hit?t28.6;r"+
      escape(document.referrer)+((typeof(screen)=="undefined")?"":
      ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
      screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
      ";"+Math.random()+
      "' alt='' title='LiveInternet: показано количество просмотров и"+
      " посетителей' "+
      "border='0' width='88' height='120'><\/a>")
      		</script>
      	</li>
        <li class="list-group-item">
           <!-- Yandex.Metrika informer -->
              <a href="https://metrika.yandex.ru/stat/?id=42728249&amp;from=informer"
              target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/42728249/3_0_20EC86FF_00CC66FF_0_pageviews"
              style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" class="ym-advanced-informer" data-cid="42728249" data-lang="ru" /></a>
            <!-- /Yandex.Metrika informer -->
        </li>
        <li class="list-group-item">
          <a href="http://yandex.ru/cy?base=0&amp;host=http://mlm-connect.net"><img src="http://www.yandex.ru/cycounter?мой_сайт" width="88" height="31" alt="Индекс цитирования" border="0" /></a>
        </li>
      </ul>
    </div>
  </div>
  <div class="hpanel">
    <div class="panel-heading hbuilt">
      <div class="panel-tools">
        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
        <a class="closebox"><i class="fa fa-times"></i></a>
      </div>
      <i class="pe pe-7s-display1 text-success"></i>
        Конвертер валют
    </div>
    <div class="panel-body no-padding" align="center">
      <iframe height="375" width="220" src="https://ssltools.forexprostools.com/currency-converter/index.php?from=17&to=12&force_lang=7">
      </iframe><br />
      <table width="197">
      	<tr>
      		<td>
      			<span style="font-size: 11px;color: #333333;text-decoration: none;">Конвертер валют от <a href="https://ru.investing.com/" rel="nofollow" target="_blank" style="font-size: 11px;color: #06529D; font-weight: bold;" class="underline_link">Investing.com Россия</a>.</span>
      		</td>
      	</tr>
      </table>
    </div>
  </div>
</div>